CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  phone VARCHAR(30) NULL,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('OWNER','ADMIN','STAFF','PARTNER','CUSTOMER') NOT NULL DEFAULT 'CUSTOMER',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  last_login_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_users_role_active (role,is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS partners (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NULL,
  business_name VARCHAR(190) NOT NULL, category VARCHAR(40) NOT NULL DEFAULT 'STAY',
  verification_status ENUM('PENDING','VERIFIED','REJECTED') NOT NULL DEFAULT 'PENDING',
  verification_reason VARCHAR(500) NULL, payout_details_encrypted TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL, INDEX idx_partners_status (verification_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS listings (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, slug VARCHAR(190) NOT NULL UNIQUE,
  partner_id BIGINT UNSIGNED NULL, category ENUM('STAY','RIDE','RENTAL','ACTIVITY') NOT NULL,
  title VARCHAR(190) NOT NULL, description TEXT NOT NULL, location VARCHAR(120) NOT NULL, address VARCHAR(255) NULL,
  base_price DECIMAL(12,2) NOT NULL DEFAULT 0, sell_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  bike_quantity INT UNSIGNED NOT NULL DEFAULT 0, scooty_quantity INT UNSIGNED NOT NULL DEFAULT 0,
  amenities JSON NULL, details JSON NULL, images JSON NULL, seo_title VARCHAR(190) NULL, seo_description VARCHAR(320) NULL,
  cancellation_policy ENUM('FLEXIBLE','MODERATE','STRICT') NOT NULL DEFAULT 'MODERATE', featured TINYINT(1) NOT NULL DEFAULT 0,
  status ENUM('DRAFT','LIVE','PAUSED','PENDING_REVIEW') NOT NULL DEFAULT 'DRAFT', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (partner_id) REFERENCES partners(id) ON DELETE SET NULL, INDEX idx_listings_filter (category,status), INDEX idx_listings_location (location)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS trips (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NULL, reference VARCHAR(32) NOT NULL UNIQUE,
  status ENUM('PENDING','CONFIRMED','COMPLETED','CANCELLED') NOT NULL DEFAULT 'PENDING', expires_at DATETIME NULL, confirmed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL, INDEX idx_trips_status_date(status,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, trip_id BIGINT UNSIGNED NULL, user_id BIGINT UNSIGNED NULL, listing_id BIGINT UNSIGNED NULL,
  category VARCHAR(30) NOT NULL, start_date DATE NULL, end_date DATE NULL, guests INT UNSIGNED NOT NULL DEFAULT 1, quantity INT UNSIGNED NOT NULL DEFAULT 1,
  rental_type VARCHAR(40) NULL, status ENUM('PENDING','CONFIRMED','COMPLETED','CANCELLED') NOT NULL DEFAULT 'PENDING', price_at_booking DECIMAL(12,2) NOT NULL DEFAULT 0,
  total_price DECIMAL(12,2) NOT NULL DEFAULT 0, commission_amount DECIMAL(12,2) NOT NULL DEFAULT 0, guest_name VARCHAR(120) NOT NULL, guest_email VARCHAR(190) NULL, guest_phone VARCHAR(30) NULL,
  metadata JSON NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (trip_id) REFERENCES trips(id) ON DELETE SET NULL, FOREIGN KEY (listing_id) REFERENCES listings(id) ON DELETE SET NULL,
  INDEX idx_bookings_status_date(status,created_at), INDEX idx_bookings_guest(guest_email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS payments (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, trip_id BIGINT UNSIGNED NOT NULL, provider_order_id VARCHAR(190) NULL, provider_payment_id VARCHAR(190) NULL,
  status ENUM('CREATED','AUTHORIZED','CAPTURED','FAILED','REFUNDED') NOT NULL DEFAULT 'CREATED', amount DECIMAL(12,2) NOT NULL DEFAULT 0, refunded_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (trip_id) REFERENCES trips(id) ON DELETE CASCADE, INDEX idx_payments_status(status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS vehicles (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, partner_id BIGINT UNSIGNED NULL, type VARCHAR(40) NOT NULL, registration_number VARCHAR(40) NOT NULL UNIQUE,
  driver_name VARCHAR(120) NULL, driver_phone VARCHAR(30) NULL, is_active TINYINT(1) NOT NULL DEFAULT 1, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (partner_id) REFERENCES partners(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS pickup_requests (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, booking_id BIGINT UNSIGNED NOT NULL UNIQUE, pickup_location VARCHAR(255) NOT NULL, dropoff_location VARCHAR(255) NULL,
  requested_time DATETIME NOT NULL, assigned_vehicle_id BIGINT UNSIGNED NULL, status ENUM('UNASSIGNED','ASSIGNED','EN_ROUTE','COMPLETED','CANCELLED') NOT NULL DEFAULT 'UNASSIGNED',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE, FOREIGN KEY (assigned_vehicle_id) REFERENCES vehicles(id) ON DELETE SET NULL, INDEX idx_pickups_status_time(status,requested_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS blog_posts (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, title VARCHAR(190) NOT NULL, slug VARCHAR(190) NOT NULL UNIQUE, excerpt TEXT NULL, body MEDIUMTEXT NOT NULL,
  category VARCHAR(100) NULL, primary_keyword VARCHAR(190) NULL, tags JSON NULL, author_id BIGINT UNSIGNED NULL, featured_image VARCHAR(255) NULL, alt_text VARCHAR(255) NULL,
  seo_title VARCHAR(190) NULL, meta_description VARCHAR(320) NULL, status ENUM('DRAFT','SCHEDULED','PUBLISHED','ARCHIVED') NOT NULL DEFAULT 'DRAFT', scheduled_at DATETIME NULL, published_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS media_assets (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, filename VARCHAR(190) NOT NULL, storage_path VARCHAR(255) NOT NULL, public_url VARCHAR(255) NOT NULL,
  mime_type VARCHAR(100) NOT NULL, size_bytes BIGINT UNSIGNED NOT NULL, width INT UNSIGNED NULL, height INT UNSIGNED NULL, alt_text VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX idx_media_type(mime_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS packages (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, title VARCHAR(190) NOT NULL, description TEXT NULL, price DECIMAL(12,2) NOT NULL DEFAULT 0,
  image VARCHAR(255) NULL, status ENUM('DRAFT','PUBLISHED','ARCHIVED') NOT NULL DEFAULT 'DRAFT', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS package_listings (package_id BIGINT UNSIGNED NOT NULL, listing_id BIGINT UNSIGNED NOT NULL, PRIMARY KEY(package_id,listing_id), FOREIGN KEY(package_id) REFERENCES packages(id) ON DELETE CASCADE, FOREIGN KEY(listing_id) REFERENCES listings(id) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS settings (`key` VARCHAR(100) PRIMARY KEY, typed_value TEXT NOT NULL, updated_by BIGINT UNSIGNED NULL, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS audit_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, actor_id BIGINT UNSIGNED NULL, action VARCHAR(80) NOT NULL, entity VARCHAR(80) NOT NULL, entity_id BIGINT UNSIGNED NULL, metadata JSON NULL, ip_address VARCHAR(45) NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(actor_id) REFERENCES users(id) ON DELETE SET NULL, INDEX idx_audit_created(created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO settings (`key`, typed_value) VALUES ('business_name','KainchiDarshan'),('commission_percent','12'),('timezone','Asia/Kolkata'),('currency','INR'),('booking_rules','{"allow_guest_checkout":true}') ON DUPLICATE KEY UPDATE `key`=`key`;
-- Create the first owner with: php scripts/create_owner.php owner@example.com "Owner Name" "strong-password"
