<?php
require __DIR__ . '/lib.php';
$path = trim(parse_url($_SERVER['REQUEST_URI'] ?? '', PHP_URL_PATH), '/');
$parts = explode('/', $path); $resource = $parts[2] ?? ''; $id = isset($parts[3]) && ctype_digit($parts[3]) ? (int)$parts[3] : null; $action = $parts[3] ?? null;
$method = $_SERVER['REQUEST_METHOD'];
try {
    if ($resource === 'auth') {
        if ($action === 'csrf' && $method === 'GET') respond(['csrf'=>csrf_token(),'user'=>actor()]);
        if ($action === 'login' && $method === 'POST') { $in=json_input(); $email=strtolower(trim($in['email']??'')); $approved=allowed_admin($email); if(!$approved) { audit('login_failed','user',null,['email'=>$email]); fail('This email is not authorized for admin access',401); } $userId=null; try { $stmt=db()->prepare('SELECT id,name,is_active FROM users WHERE email=? LIMIT 1'); $stmt->execute([$email]); $u=$stmt->fetch(); if($u && !$u['is_active']) fail('This admin account is disabled',403); if($u) { $userId=(int)$u['id']; } } catch(Throwable $e) { error_log($e->getMessage()); } $_SESSION['admin_user']=['id'=>$userId,'name'=>$approved['name'],'email'=>$email,'role'=>$approved['role']]; if($userId) db()->prepare('UPDATE users SET last_login_at=UTC_TIMESTAMP() WHERE id=?')->execute([$userId]); audit('login','user',$userId); respond(['user'=>$_SESSION['admin_user'],'csrf'=>csrf_token()]); }
        if ($action === 'logout' && $method === 'POST') { require_auth(); require_csrf(); audit('logout','user',actor()['id']); $_SESSION=[]; session_destroy(); respond(['loggedOut'=>true]); }
        fail('Not found',404);
    }
    if ($resource === 'health' && $method==='GET') { try { db()->query('SELECT 1'); respond(['database'=>'ok','php'=>PHP_VERSION,'time'=>gmdate('c')]); } catch(Throwable $e) { respond(['database'=>'degraded','time'=>gmdate('c')],200); } }
    $user=require_auth();
    if ($resource === 'dashboard' && $method==='GET') {
        $out=['bookingsToday'=>0,'revenue30'=>0,'unassignedPickups'=>0,'pendingPartners'=>0,'failedPayments'=>0,'categoryCounts'=>[],'recentOrders'=>[],'trend'=>[],'degraded'=>[]];
        $queries=['bookingsToday'=>"SELECT COUNT(*) FROM bookings WHERE DATE(created_at)=UTC_DATE()",'revenue30'=>"SELECT COALESCE(SUM(total_price),0) FROM bookings WHERE created_at >= UTC_TIMESTAMP() - INTERVAL 30 DAY AND status <> 'CANCELLED'",'unassignedPickups'=>"SELECT COUNT(*) FROM pickup_requests WHERE status='UNASSIGNED'",'pendingPartners'=>"SELECT COUNT(*) FROM partners WHERE verification_status='PENDING'",'failedPayments'=>"SELECT COUNT(*) FROM payments WHERE status='FAILED' AND created_at >= UTC_TIMESTAMP() - INTERVAL 30 DAY"];
        foreach($queries as $key=>$sql) { try { $out[$key]=(float)db()->query($sql)->fetchColumn(); } catch(Throwable $e) { $out['degraded'][]=$key; } }
        try {$out['categoryCounts']=db()->query("SELECT category,COUNT(*) count FROM bookings WHERE created_at >= UTC_TIMESTAMP() - INTERVAL 30 DAY GROUP BY category")->fetchAll();} catch(Throwable $e){$out['degraded'][]='categoryCounts';}
        try {$out['recentOrders']=db()->query("SELECT t.id,t.reference,t.status,t.created_at,COALESCE(SUM(b.total_price),0) amount,COALESCE(MAX(b.guest_name),'Guest') guest,COUNT(b.id) booking_count,COALESCE(p.status,'CREATED') payment_status FROM trips t LEFT JOIN bookings b ON b.trip_id=t.id LEFT JOIN payments p ON p.trip_id=t.id GROUP BY t.id ORDER BY t.created_at DESC LIMIT 8")->fetchAll();} catch(Throwable $e){$out['degraded'][]='recentOrders';}
        respond($out);
    }
    if ($resource === 'settings') {
        if ($method==='GET') respond(db()->query('SELECT `key`,typed_value,updated_at FROM settings ORDER BY `key`')->fetchAll());
        require_csrf(); require_auth(['OWNER','ADMIN']); $in=json_input(); $pdo=db(); $pdo->beginTransaction(); foreach($in as $key=>$value) { if(!preg_match('/^[a-z0-9_]+$/',$key)) continue; $s=$pdo->prepare('INSERT INTO settings (`key`,typed_value,updated_by) VALUES(?,?,?) ON DUPLICATE KEY UPDATE typed_value=VALUES(typed_value),updated_by=VALUES(updated_by),updated_at=UTC_TIMESTAMP()'); $s->execute([$key,is_scalar($value)?(string)$value:json_encode($value),$user['id']]); } $pdo->commit(); audit('edit','settings',null,['keys'=>array_keys($in)]); respond(['saved'=>true]);
    }
    if ($resource === 'listings') {
        if ($method==='GET') { $where=['1=1']; $params=[]; if(!empty($_GET['search'])){$where[]='(l.title LIKE ? OR l.location LIKE ? OR p.business_name LIKE ?)';$q='%'.clean_text($_GET['search'],100).'%';$params=[$q,$q,$q];} if(!empty($_GET['category'])){$where[]='l.category=?';$params[]=$_GET['category'];} if(!empty($_GET['status'])){$where[]='l.status=?';$params[]=$_GET['status'];} $w=implode(' AND ',$where); paged("SELECT l.*,p.business_name partner_name FROM listings l LEFT JOIN partners p ON p.id=l.partner_id WHERE $w ORDER BY l.created_at DESC",$params,"SELECT COUNT(*) FROM listings l LEFT JOIN partners p ON p.id=l.partner_id WHERE $w",$params); }
        require_csrf(); if($method==='DELETE' && $id){ $s=db()->prepare('SELECT COUNT(*) FROM bookings WHERE listing_id=?');$s->execute([$id]);if($s->fetchColumn()>0)fail('Listing has bookings and cannot be deleted',409);db()->prepare('DELETE FROM listings WHERE id=?')->execute([$id]);audit('delete','listing',$id);respond(['deleted'=>true]); }
        if(in_array($method,['POST','PATCH'],true)){ $in=json_input(); $errors=[]; foreach(['title','category','location'] as $field) if(empty($in[$field]))$errors[$field]='Required'; $base=(float)($in['base_price']??0);$sell=(float)($in['sell_price']??0);if($base<0||$sell<0||$sell<$base)$errors['sell_price']='Selling price must be >= base price';if($errors)fail('Please fix the highlighted fields',422,$errors);$values=[clean_text($in['slug']??preg_replace('/[^a-z0-9]+/i','-',strtolower($in['title']))),clean_text($in['title'],190),clean_text($in['description']??'',5000),clean_text($in['location'],120),$in['category'],$base,$sell,$in['status']??'DRAFT',json_encode($in['amenities']??[])];if($method==='POST'){$s=db()->prepare('INSERT INTO listings (slug,title,description,location,category,base_price,sell_price,status,amenities) VALUES(?,?,?,?,?,?,?,?,?)');$s->execute($values);$id=db()->lastInsertId();}else{$values[]=$id;$s=db()->prepare('UPDATE listings SET slug=?,title=?,description=?,location=?,category=?,base_price=?,sell_price=?,status=?,amenities=? WHERE id=?');$s->execute($values);}audit($method==='POST'?'create':'edit','listing',$id);respond(['id'=>(int)$id]);}
    }
    $simpleMap=['customers'=>['table'=>'users','label'=>'customer','where'=>"role='CUSTOMER'"],'users'=>['table'=>'users','label'=>'user','where'=>"role IN ('OWNER','ADMIN','STAFF')"],'partners'=>['table'=>'partners','label'=>'partner','where'=>'1=1'],'vehicles'=>['table'=>'vehicles','label'=>'vehicle','where'=>'1=1'],'pickups'=>['table'=>'pickup_requests','label'=>'pickup','where'=>'1=1'],'media'=>['table'=>'media_assets','label'=>'media','where'=>'1=1'],'packages'=>['table'=>'packages','label'=>'package','where'=>'1=1'],'blog'=>['table'=>'blog_posts','label'=>'blog_post','where'=>'1=1']];
    if(isset($simpleMap[$resource])) { $m=$simpleMap[$resource]; if($method==='GET'){ $search=clean_text($_GET['search']??'',100);$where=$m['where'];$params=[];if($search && $resource==='users'){$where.=' AND (name LIKE ? OR email LIKE ?)';$params=["%$search%","%$search%"]; } if($search && $resource==='partners'){$where.=' AND business_name LIKE ?';$params=["%$search%"]; } paged("SELECT * FROM {$m['table']} WHERE $where ORDER BY created_at DESC",$params,"SELECT COUNT(*) FROM {$m['table']} WHERE $where",$params); } require_csrf(); require_auth(['OWNER','ADMIN']); if($method==='DELETE'&&$id){db()->prepare("DELETE FROM {$m['table']} WHERE id=?")->execute([$id]);audit('delete',$m['label'],$id);respond(['deleted'=>true]);} if(in_array($method,['POST','PATCH'],true)){ $in=json_input(); if($resource==='users'&&$method==='POST'){if(empty($in['email'])||empty($in['name'])||empty($in['password']))fail('Name, email, and password are required',422);$s=db()->prepare('INSERT INTO users(name,email,password_hash,role,is_active) VALUES(?,?,?,?,?)');$s->execute([clean_text($in['name'],120),strtolower(trim($in['email'])),password_hash($in['password'],PASSWORD_DEFAULT),$in['role']??'STAFF',1]);$id=db()->lastInsertId();} elseif($resource==='partners'&&$method==='POST'){ $s=db()->prepare('INSERT INTO partners(business_name,category,verification_status) VALUES(?,?,?)');$s->execute([clean_text($in['business_name'],190),$in['category']??'STAY',$in['verification_status']??'PENDING']);$id=db()->lastInsertId();} else {fail('This resource supports read and delete in the starter workflow',405);} audit('create',$m['label'],$id);respond(['id'=>(int)$id]); } }
    if ($resource === 'orders' && $method==='GET') { $where='1=1';$params=[];if(!empty($_GET['search'])){$where.=' AND (t.reference LIKE ? OR b.guest_name LIKE ? OR b.guest_email LIKE ? OR b.guest_phone LIKE ?)';$q='%'.clean_text($_GET['search'],100).'%';$params=[$q,$q,$q,$q];}if(!empty($_GET['status'])){$where.=' AND t.status=?';$params[]=$_GET['status'];}paged("SELECT t.*,COALESCE(MAX(b.guest_name),'Guest') guest,COALESCE(SUM(b.total_price),0) amount,COUNT(b.id) booking_count FROM trips t LEFT JOIN bookings b ON b.trip_id=t.id WHERE $where GROUP BY t.id ORDER BY t.created_at DESC",$params,"SELECT COUNT(DISTINCT t.id) FROM trips t LEFT JOIN bookings b ON b.trip_id=t.id WHERE $where",$params); }
    fail('Endpoint not found',404);
} catch(PDOException $e) { error_log($e->getMessage()); fail('A database operation failed',500); } catch(Throwable $e) { error_log($e->getMessage()); fail('Unexpected server error',500); }
